### PR TITLE
[DEV-573] Speed up star select from push commits view by 100x

### PR DESCRIPTION
**Pull request by vmarkovtsev**

### CODE REVIEW

**Comment by vmarkovtsev** [comment]
I am not using them so I dropped them. Are they needed?

**Comment by dennwc** [comment]
@vmarkovtsev Yes, I use them sometimes for debugging purposes, least in a `UNION` views like `github_authors`.

**Comment by vmarkovtsev** [comment]
OK, returning them back then.

**Comment by vmarkovtsev** [comment]
@dennwc done

**Pull request merged**
